### ISSUE TITLE
Access to Text Content?

### ISSUE THREAD

**Issue by kalvenschraut** [FranckFreiburger/vue-pdf#10]
I see there is a to do of allowing access to the text content of the page, I was wondering if this is being worked on/how far along it is? I have been looking for the ability to tie in pdfs into my vuejs components, but I do need the ability to access the text content of PDFs. Otherwise this project looks promising and really one of the only solutions to my issue.

**Comment by FranckFreiburger** [comment]
see https://github.com/FranckFreiburger/vue-pdf#example---get-text-content
