### ISSUE TITLE
Watermark is not shown

### ISSUE THREAD

**Issue by TimYi** [FranckFreiburger/vue-pdf#102]
- vue-pdf 3.3.1
- vue.js 2.5.16
- webpack 4.16.1
- browser latest chrome and firefox
- OS both ubuntu 16.04 and windows 10
- error file [hetong.pdf](https://github.com/FranckFreiburger/vue-pdf/files/2207900/hetong.pdf)
There is watermark inside this pdf, but the watermark is not rendered by vue-pdf.

**Comment by FranckFreiburger** [comment]
waiting for next mozilla/pdfjs-dist release ...
