### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by mgobishop** [FranckFreiburger/vue-pdf#105]
I have included vue-pdf in my application but it now fails to build:

SyntaxError: Unexpected token (2:0) while parsing vuePdfNoSss.vue while parsing file: node_modules/vue-pdf/src/vuePdfNoSss.vue
    at DestroyableTransform.end [as _flush] (node_modules/insert-module-globals/index.js:107:21)

I'm building using babelify, etc:

browserify -t vueify -e ./src/vue.js -o dist/bundle.js -t [ babelify --presets [ 'es2016' ] ]

Any help would be appreciated :-)

**Comment by michelleLegend** [comment]
Same issue:

[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
~/node_modules/vue-pdf/src/vuePdfNoSss.vue:1
(function (exports, require, module, __filename, __dirname) { <script>

**Comment by tpin85** [comment]
Exactly same issue. 
Use with nuxt js.

**Comment by tpin85** [comment]
Hello,
Component work fine when app is fully loaded. But when i refresh the page or if i'm landing directly on this page i get a nuxt error.

logs says
> render function or template not defined in component: anonymous

if i look deeper it's vue-server-renderer who return an error.

for fun i've try to use but the issue stay the same.

Anyone have an idea to solve this ?

thanks.

--sorry for my english, my french is better--

**Comment by BrunoLambert** [comment]
Same problem here.

**Comment by FranckFreiburger** [comment]
Duplicate of #13

**Comment by evatxu** [comment]
same question. how to fix?

**Comment by songjishuai** [comment]
I also encountered the same problem. Is there a solution?
