### ISSUE TITLE
not working in project generated from vue-cli3 - does work in vue-cli2 generated project

### ISSUE THREAD

**Issue by focussing** [FranckFreiburger/vue-pdf#108]
Could you please fix or give a work-around?

The following error occurs:

Uncaught ReferenceError: window is not defined
(anonymous) @ 201a41b776ad02854bfa.worker.js:2
(anonymous) @ 201a41b776ad02854bfa.worker.js:792

**Comment by focussing** [comment]
maybe this error has a relation with https://github.com/rossta/vue-pdfjs-demo/issues/3 ?

**Comment by hannajs** [comment]
Edit (or create) vue.config.js and change webpack configuration there:
`module.exports = {
configureWebpack: config => {
    config.output.globalObject = "this";
  }
}`

**Comment by focussing** [comment]
I created a new project based on vue cli 3.0.5 and it works! :)

**Comment by FranckFreiburger** [comment]
see #97
