### ISSUE TITLE
Render multiple pages/whole document

### ISSUE THREAD

**Issue by hendrikschneider** [FranckFreiburger/vue-pdf#11]
Hi,

is it possible to render multiple pages at once?

**Comment by andreasvirkus** [comment]
Ping, any ETA on this?

**Comment by andreasvirkus** [comment]
I currently used an ugly workaround:
```
<template>
  <section>
    <spinner v-if="loading">
    <template v-else>
      <!-- Need to load a single page to get page count -->
      <pdf style="display: none;" :src="contract"
        class="contract-container"
        @num-pages="pageCount = new Array($event)" />
      <pdf v-for="(page, index) in pageCount"
        :key="index"
        :src="contract"
        :page="index + 1"
        class="contract-container" />
    </template>
  </section>
</template>

<script>
  import pdf from 'vue-pdf';

  export defualt {
    components: { pdf },
    data() {
      return {
        loading: true,
        pageCount: [],
        contract: { data: '' }
      }
    }
  }
</script>  
```

**Comment by FranckFreiburger** [comment]
see https://github.com/FranckFreiburger/vue-pdf#example---display-multiple-pages-of-the-same-pdf-document

**Comment by jerrychong25** [comment]
If u wanna with scroll whole PDF document with full size pages, using @FranckFreiburger ([https://github.com/FranckFreiburger/vue-pdf#example---display-multiple-pages-of-the-same-pdf-document](https://github.com/FranckFreiburger/vue-pdf#example---display-multiple-pages-of-the-same-pdf-document)) example, plus just change styling to **height with 100%**, as per following:

```
<pdf
     v-for="i in numPages"
     :key="i"
     :src="src"
     :page="i"
     style="height: 100%"
></pdf>
```

Then it will be working as per expected.
