### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by patientplatypus** [FranckFreiburger/vue-pdf#112]
Your demo just shows a blank page:
https://imgur.com/a/RseggLR
When I try and use your example code in my browser using a known good pdf I also get a blank space.
Please either update the fiddle or the readme or fix the bugs.

**Comment by Mrjianghan** [comment]
me too

**Comment by ahKevinXy** [comment]
me ye too

**Comment by FranckFreiburger** [comment]
see #78
