### ISSUE TITLE
ios8 appear error！

### ISSUE THREAD

**Issue by guodongzzzZ** [FranckFreiburger/vue-pdf#116]
I have already done it  pdfjsWrapper.js line 223 'const' to 'var，but the error alreardy have.

11.23  i npm install once again，it appear error later.

my english is bad, sorry.

thanks to your see.
 - provide:
     - vue-pdf 3.3.1
     - vue.js 2.5.2
     - webpack 3.6.0
     - browser 
     - OS 8.4.1

error info： 
Unexpected token '('. Expected a ':' following the property name 'toString'.

**Comment by FranckFreiburger** [comment]
please provide a complete stacktrace of your exception

**Comment by FranckFreiburger** [comment]
ping!

**Comment by FranckFreiburger** [comment]
Closed due to the lack of activity.
