### ISSUE TITLE
import pdf from 'vue-pdf' error

### ISSUE THREAD

**Issue by TigerLiv** [FranckFreiburger/vue-pdf#121]
npm install --save vue-pdf,
when import,  makes error

[eslint] Missing file extension "vue" for "vue-pdf" [import/extensions]

why?

**Comment by FranckFreiburger** [comment]
Can you provide more details about the location of this issue ?

**Comment by TigerLiv** [comment]
> Can you provide more details about the location of this issue ?

i used  vue-cli3 
package.json  "dependencies": {
    "vue": "^2.5.17",
    "vue-pdf": "^4.0.3",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },

<template>
  <div class="hello">
    <pdf src="https://cdn.mozilla.net/pdfjs/tracemonkey.pdf"></pdf>
  </div>
</template>

<script>
import pdf from 'vue-pdf';

export default {
  name: 'HelloWorld',
  data() {
    return {

    };
  },
  components: {
    pdf,
  },
};
</script>


<style scoped>

</style>

**Comment by TigerLiv** [comment]
> Can you provide more details about the location of this issue ?

Module Warning (from ./node_modules/_eslint-loader@2.1.1@eslint-loader/index.js):
error: Missing file extension "vue" for "vue-pdf" (import/extensions) at src/components/HelloWorld.vue:8:17:
   6 |
   7 | <script>
>  8 | import pdf from 'vue-pdf';
     |                 ^
   9 |
  10 | export default {
  11 |   name: 'HelloWorld',

**Comment by TigerLiv** [comment]
OK I solved  and use vue.cli 2

**Comment by FranckFreiburger** [comment]
how did you solve this issue ?

**Comment by TigerLiv** [comment]
> how did you solve this issue ?
I used vue-cli3.0  before, then i use vue-cli2.0  to generate the project，and solved it.

**Comment by SupaFan** [comment]
What if we don't use cli2

**Comment by SupaFan** [comment]
1. add eslint-import-resolver-webpack
`yarn add eslint-import-resolver-webpack`

2. edit .eslintrc.js 

```
settings: {
    'import/resolver': {
      webpack: {
        config: 'node_modules/@vue/cli-service/webpack.config.js',
      },
    },
  },
```
```
rules: {
    'import/extensions': ['error', 'always', {
      'js': 'never',
      'vue': 'never'
    }]
  },
```
