### ISSUE TITLE
can not render a Scanned pdf 

### ISSUE THREAD

**Issue by small752** [FranckFreiburger/vue-pdf#125]
"version": "3.3.1"
can not render a Scanned pdf .

**Comment by small752** [comment]
Warning: Unable to decode image: RangeError: Array buffer allocation failed
Warning: Dependent image isn't ready yet

**Comment by FranckFreiburger** [comment]
As mentioned in my issue template, test your pdf at http://mozilla.github.io/pdf.js/web/viewer.html?file=

**Comment by FranckFreiburger** [comment]
closing this issue until you give more information.
