### ISSUE TITLE
Template display blank PDF

### ISSUE THREAD

**Issue by HarisHashim** [FranckFreiburger/vue-pdf#129]
Info
---

     - vue-pdf version: 4.05
     - vue.js version: 2.9.6 
     - webpack version: 4.19.1
     - browser version: 73.0.3657.0 (Official Build) canary (32-bit)
     - OS version: Win10 Pro 1803

Problem
---------

Using Vue-pdf with Quasar Framework v17. Give blank pdf.

![image](https://user-images.githubusercontent.com/1856131/50580638-17432f00-0e8c-11e9-9060-31bca9ee11f0.png)

Bellow error in chrome devtool console

```
e8ff547e9f6f8b04698b.worker.js:2 Uncaught ReferenceError: window is not defined
    at e8ff547e9f6f8b04698b.worker.js:2
    at e8ff547e9f6f8b04698b.worker.js:792
```

My google search lead to https://github.com/webpack/webpack/issues/6642 .

Is this a known issue? Any workaround?

Bellow is just a bit of code snippet, not everything.

```
<template>
   <pdf src="http://www.pdf995.com/samples/pdf.pdf" />
</template>
<script>
import PageWidget from "components/widget/PageWidget";
import pdf from "vue-pdf";

export default {
  components: {
    PageWidget,
    pdf
  },
//...
</script>

```

**Comment by HarisHashim** [comment]
Take note that jsfiddle example in the README also give blank page.

**Comment by FranckFreiburger** [comment]
dup #97

**Comment by FlyingFishPeng** [comment]
Have you ever resolved this problem ？？I have the same problem with you

**Comment by ynuchenqian** [comment]
me,too.How to deal with?

**Comment by terajoellang** [comment]
Same problem here, was anyone able to resolve it?
