### ISSUE TITLE
vue-pdf failed to compile

### ISSUE THREAD

**Issue by vedrao** [FranckFreiburger/vue-pdf#134]
INFO  Starting development server...
 ERROR  Failed to compile with 1 errors16:14:34

 error  in ./node_modules/vue-pdf/src/pdfjsWrapper.js

Module parse failed: Unexpected token (27:11)
You may need an appropriate loader to handle this file type.
| 			this.fetch = function(query) {
| 
> 				return import('raw-loader!pdfjs-dist/cmaps/'+query.name+'.bcmap' /* webpackChunkName: "noprefetch-[request]" */)
| 				.then(function(bcmap) {
|

**Comment by FranckFreiburger** [comment]
need more details (versions)

**Comment by FranckFreiburger** [comment]
If you are using the latest webpack (4.29.0), you encounter the following issue: 
https://github.com/webpack/webpack/issues/8656
