### ISSUE TITLE
How to modify PDF files dynamically ?

### ISSUE THREAD

**Issue by XXXS** [FranckFreiburger/vue-pdf#139]
<template> <pdf  v-for="i in numPages"  :key="i":src="src"  :page="i" style="display: inline-block; width: 100%" ></pdf></template>
<script>
    import pdf from 'vue-pdf'
    var loadingTask = pdf.createLoadingTask('https://cdn.mozilla.net/pdfjs/tracemonkey.pdf');
    export default {
        components: {  pdf  },
        data() {
            return {
                numPages: undefined,
                pdfUrl:"",
                src:loadingTask,
            }
        },
        created() {
            axios.get(url).then(res => {
               // get the data    modify the PDF file path
                   if (res) { this.src = res.pdUrl; }
                })
        },
        mounted() {
            this.src.then(pdf => {
                this.numPages = pdf.numPages;
            });
        },} }
</script>

**Comment by FranckFreiburger** [comment]
Sorry, no plans to add that feature.
vue-pdf is a PDF viewer only.

**Comment by XXXS** [comment]
Sorry, maybe I didn't explain it.  When I Preview PDF with vue-pdf, how do I modify the path of the PDF file.  Thank you

**Comment by FranckFreiburger** [comment]
Just update the `src` property (see [documentation](https://github.com/FranckFreiburger/vue-pdf#src-string--object---default-))

**Comment by FranckFreiburger** [comment]
does it work ?
