### ISSUE TITLE
Print preview file garbled

### ISSUE THREAD

**Issue by shengbid** [FranckFreiburger/vue-pdf#145]
![PDF1](https://user-images.githubusercontent.com/35691811/54672358-ce1d8580-4b32-11e9-8a92-691214cfea04.png)

`<el-button @click="$refs.myPdfComponent.print()">print</el-button>
    <pdf ref="myPdfComponent" :src="src"></pdf>`

Click print, file preview garbled

 - provide:
     - vue-pdf 3.3.1
     - vue.js 2.5.2
     - webpack 3.6.0
     - browser Chrome
     - OS version

pdf file: 
[pdf.pdf](https://github.com/FranckFreiburger/vue-pdf/files/2987336/pdf.pdf)

**Comment by anchoretics** [comment]
@shengbid 看下 https://github.com/FranckFreiburger/vue-pdf/pull/130
用这个fix，预览就不乱码了

**Comment by shengbid** [comment]
Thank you. That's settled

**Comment by Mrjianghan** [comment]
> 用这个fix，预览就不乱码了

不，那个修复在多页的情况下，依旧有bug

**Comment by martintan** [comment]
I'm still getting this issue

**Comment by Mrjianghan** [comment]
> I'm still getting this issue

@shengbid 看下 #130
用这个fix，预览就不乱码了
