### ISSUE TITLE
tips font error

### ISSUE THREAD

**Issue by abb6512** [FranckFreiburger/vue-pdf#152]
I was prompted to a mistake when loading PDF, seems to be caused by the font, I use Chinese fonts here, how should I set it?

Warning: Unimplemented widget field type "Sig", falling back to base field type.
Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.

**Comment by FranckFreiburger** [comment]
You must use CMapReaderFactory:
 
```
import CMapReaderFactory from 'vue-pdf/src/CMapReaderFactory.js'
...
.createLoadingTask({ // https://github.com/FranckFreiburger/vue-pdf#createloadingtasksrc
				url: ...
				CMapReaderFactory
})
```

**Comment by abb6512** [comment]
There are new problems with using your code.

Warning: Unimplemented widget field type "Sig", falling back to base field type.
 Warning: Error during font loading: Module build failed: TypeError: loaderUtils.getOptions is not a function at Object.module.exports (C:\Users\zhangzg.TSTA\Desktop\tttt\operator\node_modules\vue-pdf\src\buffer-loader.js:5:28)

**Comment by abb6512** [comment]
I'm a novice. I'm bothering you.

**Comment by abb6512** [comment]
this pdf is https://down.szhtxx.cn/downPdf/440301999999980/2019/04/18/4370207866553344.pdf
can you help me ?

**Comment by chenixhn** [comment]
你好，你这个问题是由于发票涉及电子签章引起的。找到此组件依赖的pdf_dist 文件夹中的pdf.worker.js文件，注释此代码段。
if (data.fieldType === 'Sig') {
   _this2.setFlags(_util.AnnotationFlag.HIDDEN);
}
实测可以展示电子签章。但是会报一个没有授权库的警告。不影响使用。

**Comment by FranckFreiburger** [comment]
@chenixhn please use English langage.

**Comment by shuiwangwang** [comment]
I use  CMapReaderFactory:
```
import pdf from 'vue-pdf'
import CMapReaderFactory from 'vue-pdf/src/CMapReaderFactory.js'
pdf.createLoadingTask({
	url: ''
	CMapReaderFactory
})
```
but the following problem was occurred

warning  in ./node_modules/pdfjs-dist/cmaps/78-EUC-V.bcmap
Module build failed (from ./node_modules/vue-pdf/src/buffer-loader.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.module.exports (/Users/lemon/test/web/node_modules/vue-pdf/src/buffer-loader.js:5:28)

I view the source code in buffer-loader.js:5:28. I use loader-utils@0.2.17 version.
![image](https://user-images.githubusercontent.com/8505261/58528141-fba83e80-8207-11e9-9434-1d043d827805.png)

**Comment by FranckFreiburger** [comment]
fix: https://github.com/FranckFreiburger/vue-pdf/commit/ab13216818d575ec6131d448fc95fd573debc7e4

**Comment by FranckFreiburger** [comment]
available in v4.0.7

**Comment by chenixhn** [comment]
@FranckFreiburger No, I can't because I'm from China.

**Comment by YangPengFe1** [comment]
I used it in my project and the bug is that my Chinese pdf cannot be displayed normally。
Does anyone know when this bug can be solved or how to deal with it？

**Comment by YangPengFe1** [comment]
https://github.com/FranckFreiburger/vue-pdf/issues/152#issuecomment-495053321
你好 你这样解决了这个问题吗？

**Comment by CHEN-DONG** [comment]
if there any ex for CMapReaderFactory
