### ISSUE TITLE
Kind of pagination pdf

### ISSUE THREAD

**Issue by eduardoha70** [FranckFreiburger/vue-pdf#153]
Hello, is there any way to create a kind of pagination with pages of pdf, For instance i have a pdf file with 100 pages, at the beginning only the first 5 pages are loaded and then user wants to see 
remaining pages these are loaded

     - vue-pdf version: 4.06
     - vue.js version: 2.5.9
     - webpack version: 3.12
     - browser version: Chrome 72.0.3626.12
     - OS version: Linux ubuntu 16.04

**Comment by FranckFreiburger** [comment]
The following example may help you: https://github.com/FranckFreiburger/vue-pdf#example---display-multiple-pages-of-the-same-pdf-document
Using `createLoadingTask()` will let you have multiple view of the same pdf document.
