### ISSUE TITLE
The pdf display is too narrow and there are too many white margins around the page. Can I set the display ratio of the pdf in the page?

### ISSUE THREAD

**Issue by lxmbetterman** [FranckFreiburger/vue-pdf#154]

**Comment by wenh7788** [comment]
我也有同样的问题

**Comment by FranckFreiburger** [comment]
Please look at the following issue https://github.com/FranckFreiburger/vue-pdf/issues/15
(and **please**, pay attention to the "IMPORTANT" notice when you file an issue)
