### ISSUE TITLE
vue-pdf Unimplemented annotation type "BJCA:Annot"

### ISSUE THREAD

**Issue by fanGuangqing** [FranckFreiburger/vue-pdf#164]
hello，I was prompted to a mistake when loading PDF,I use Chinese fonts here,how should I set it?

Warning: Unimplemented annotation type "BJCA:Annot", falling back to base annotation.
Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.

I hope you can help me. Thank you

**Comment by FranckFreiburger** [comment]
You have to use CMap factory, see https://github.com/FranckFreiburger/vue-pdf/issues/152#issuecomment-484382497
