### ISSUE TITLE
I got so many warning like this:Ignoring invalid character "xxx" in hex string

### ISSUE THREAD

**Issue by Rooaw** [FranckFreiburger/vue-pdf#166]
<img width="309" alt="屏幕快照 2019-07-06 下午8 05 15" src="https://user-images.githubusercontent.com/15188374/60755932-721b3600-a029-11e9-8b45-0652a43597ed.png">

**Comment by huoruji** [comment]
我也遇到了，pdf页数太多的时候就会出现这个warning，并且pdf加载不出来

**Comment by huoruji** [comment]
I have the same question too,and to many pages in a PDF file, the pages are not displayed

**Comment by Rooaw** [comment]
> I have the same question too,and to many pages in a PDF file, the pages are not displayed

my PDF just only nine pages. It's also doesn't work.

**Comment by huoruji** [comment]
@Rooaw 我之前的pdf的src路径写的是相对路径，我把本地的pdf放到了static文件夹下面，就可以加载了

**Comment by wilsunson** [comment]
it is because of the pragram can not find out your pdf files,if you build with  vue cli3,put your pdf under public document,  if vue 2.x, to static

**Comment by SnowZhouJ** [comment]
@wilsunson I tried, but failed, Can you give a sample code

**Comment by wilsunson** [comment]
> @wilsunson I tried, but failed, Can you give a sample code

你如果是用vuecli3构建的项目，把你的pdf文件放在pubilc/pdf文件夹下，引用的时候用src='./pdf/你的文件名'，如果是vue cli2.x，放到static/pdf，引用路径一样

**Comment by SnowZhouJ** [comment]
@wilsunson 我的版本是2.9.6  放在static目录和，放在src/assets目录 都不行 
./xx.pdf 只能获取同目录下文件。

**Comment by wilsunson** [comment]
> @wilsunson 我的版本是2.9.6 放在static目录和，放在src/assets目录 都不行
> ./xx.pdf 只能获取同目录下文件。

这样的话你就用相对路径呗，用../../../直到你的static目录下，我说的是访问本地服务的写法:localhost:8080+/static/pdf/yourpdf.pdf,这种方法可以拼接，好用点。

**Comment by SnowZhouJ** [comment]
@wilsunson 基本可以确定是src地址的文件没有找到导致，也就是src地址不对。 目前我的系统是前后端分离的，不知这种情况该如何配置src，因为文件在后端服务器上。 此pdf插件的src是否支持从后台下载文件流的方式进行赋值展示？

**Comment by wilsunson** [comment]
> @wilsunson 基本可以确定是src地址的文件没有找到导致，也就是src地址不对。 目前我的系统是前后端分离的，不知这种情况该如何配置src，因为文件在后端服务器上。 此pdf插件的src是否支持从后台下载文件流的方式进行赋值展示？

:src = "后端地址+'/pdfName.pdf'", 拼接呗，这个pdf插件是支持文件流的。

**Comment by SnowZhouJ** [comment]
@wilsunson 通过文件流方式已经可以了，多谢相助。静态地址的方式貌似没找到问题点在哪，暂时也没有这种使用场景就不过多追究了

**Comment by TetsuGuy** [comment]
https://github.com/mozilla/pdf.js/issues/4244

**Comment by FETE-CH** [comment]
> > @wilsunson I tried, but failed, Can you give a sample code
> 
> 你如果是用vuecli3构建的项目，把你的pdf文件放在pubilc/pdf文件夹下，引用的时候用src='./pdf/你的文件名'，如果是vue cli2.x，放到static/pdf，引用路径一样

一语惊醒，感谢

**Comment by JamieZAZA** [comment]
哈哈哈哈，可以！！ @wilsunson

**Comment by shijiezhou1** [comment]
> > @wilsunson I tried, but failed, Can you give a sample code
> 
> 你如果是用vuecli3构建的项目，把你的pdf文件放在pubilc/pdf文件夹下，引用的时候用src='./pdf/你的文件名'，如果是vue cli2.x，放到static/pdf，引用路径一样

Let me translate this for those people who get the same errors and can't figure it out. 

if you use vue-cli 3 to build your project.

put the pdf file in the public/pdf folder and then 
```
<pdf src="./pdf/something.pdf"></pdf>
```

if you use vue-cli 2 to build your project. 
```
<pdf src="static/something.pdf"></pdf>
```

Please close this issues thank you

**Comment by wilsunson** [comment]
> > > @wilsunson I tried, but failed, Can you give a sample code
> > 
> > 
> > 你如果是用vuecli3构建的项目，把你的pdf文件放在pubilc/pdf文件夹下，引用的时候用src='./pdf/你的文件名'，如果是vue cli2.x，放到static/pdf，引用路径一样
> 
> Let me translate this for those people who get the same errors and can't figure it out.
> 
> if you use vue-cli 3 to build your project.
> 
> put the pdf file in the public/pdf folder and then
> 
> ```
> <pdf src="./pdf/something.pdf"></pdf>
> ```
> 
> if you use vue-cli 2 to build your project.
> 
> ```
> <pdf src="static/something.pdf"></pdf>
> ```
> 
> Please close this issues thank you

i would like to close it,but i am sorry i am not the one who open this issue...
