### ISSUE TITLE
some PDF in ios isn't show

### ISSUE THREAD

**Issue by ztxchong** [FranckFreiburger/vue-pdf#170]

**Comment by 1129802181** [comment]
我目前是一个pdf显示一部分，有部分页面是空白，有遇到吗

**Comment by ztxchong** [comment]
那应该是字体问题

**Comment by li704644993** [comment]
> 我目前是一个pdf显示一部分，有部分页面是空白，有遇到吗

我也遇到了。请问解决了吗

**Comment by ztxchong** [comment]
> > 我目前是一个pdf显示一部分，有部分页面是空白，有遇到吗
> 
> 我也遇到了。请问解决了吗

应该都是字体问题吧，我是换个英文名字字体就好了
