### ISSUE TITLE
run dev error

### ISSUE THREAD

**Issue by LJH520** [FranckFreiburger/vue-pdf#173]
This dependency was not found:

* babel-runtime/regenerator in ./node_modules/pdfjs-dist/lib/web/ui_utils.js

To install it, you can run: npm install --save babel-runtime/regenerator

**Comment by LJH520** [comment]
npm i --save babel-runtime

**Comment by Balex70** [comment]
First of all, nice package. Would be nice to have mention about "npm i --save babel-runtime" in README though :)
