### ISSUE TITLE
[Bug] Breaks when going fast (Error: Cannot use the same canvas during multiple render() operations)

### ISSUE THREAD

**Issue by rayfoss** [FranckFreiburger/vue-pdf#18]
Changing pages quickly breaks the component permanently. If you listen to @error you'll get: 
```
Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
    at InternalRenderTask_initializeGraphics [as initializeGraphics] (api.js:2227)
    at api.js:894
    at <anonymous>
```

Steps to reproduce
1. Use Chrome 62, vue-pdf >=1.2, <=3.1
2. visit https://fiddle.jshell.net/fossfiddler/5k4ptmqg/149/
3. click in the input box, make sure the cursor is ready for input
4. press and hold up arrow till you reach page 14
5. If page 14 loaded, refresh the page, go to `MacOS Settings -> Keyboard -> Key Repeat` set it to "fast" and try again this time going backwards as well after going forward.

quod erat demonstrandum:
https://fiddle.jshell.net/fossfiddler/5k4ptmqg/149/
![gonzales](https://user-images.githubusercontent.com/876076/34693113-1c5729fc-f488-11e7-9169-1564d6381fd2.gif)

Expected result:
Page 14 should load

Actual result:
Page loading completely breaks after a certain page and does not come back

Workarounds:
throttling the page change with debounce or throttle

if you try to restart the component you may get this error aswell:
```
pdf.worker.js?1385:13862 Uncaught (in promise) Error: Request was aborted
    at ChunkedStreamManager_abort [as abort] (pdf.worker.js?1385:13862)
    at NetworkPdfManager_terminate [as terminate] (pdf.worker.js?1385:41380)
    at wphTerminate (pdf.worker.js?1385:25059)
    at eval (pdf.worker.js?1385:1081)
    at <anonymous>
```

**Comment by hurkanyakay** [comment]
I also faced that problem.Any ideas?

**Comment by rayfoss** [comment]
debounce or throttle
```
  setPage: debounce(
      function (page) { // vue-pdf breaks if flipping 1 -> ~30 / 40
        let validated = page <= this.numPages && page >= 1 ? page : this.page
        this.page = validated
        this.fakePage = validated
      }, 100)
```

**Comment by rayfoss** [comment]
@hurkanyakay 3.1 clearly fixed this, It now generates these good errors:

RenderingCancelledException {message: "Rendering cancelled, page 9", type: "canvas"}

**Comment by rayfoss** [comment]
Strangely, it seems somewhat fine in the simplest case going forward with 3.1, not when going backward however. In my production pdf it breaks on page 25+ going forward.

with a range it's easier to see:

```
Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
    at InternalRenderTask_initializeGraphics [as initializeGraphics] (api.js:2227)
    at api.js:894
    at <anonymous>
```
https://fiddle.jshell.net/fossfiddler/5k4ptmqg/149/
![gonzales](https://user-images.githubusercontent.com/876076/34693113-1c5729fc-f488-11e7-9169-1564d6381fd2.gif)


The 100ms debounce workaround still works.

**Comment by FranckFreiburger** [comment]
I understand that a debouncing could fix the issue, but I need to find a more robust fix, I think it's just a  canvas access synchronisation issue ...
