### ISSUE TITLE
Getting a local PDF to be displayed

### ISSUE THREAD

**Issue by mohammedpatla** [FranckFreiburger/vue-pdf#187]
Vue-PDF : 4.0.7
Vue.js : 2.6.10
OS Version: Mac OS 10.15
browser : firefox 70.0
I was playing around and the :src prop only accepts 'http://example.com/pdf.pdf' PDF file. I am unable to access a local file like '../public/mypdf.pdf'
I believe this is an other issue or related with CORS request but am not sure.
Or am i doing something wrong?

**Comment by telfordNiu** [comment]
1. vue.config.js  or  webpack.config.js  add module:
`            rules: [
                { test: /\.pdf$/, use: 'file-loader' }
            ]`
2.  src use  data  reqire pdf file path
`<template>
    <div>
        <pdf :src="pdfUrl"></pdf>
    </div>
</template>`

`        data() {
            return {
                pdfUrl:require("../../../assets/11.pdf")
            }
        }`

**Comment by mohammedpatla** [comment]
Thank you, it seems it was more of Vuu.js issue where it wont access local files.
