### ISSUE TITLE
Retina Display support

### ISSUE THREAD

**Issue by rayfoss** [FranckFreiburger/vue-pdf#19]
it seems that the resizeSensor hooks give density independent pixels... when ideally we'd rather have a canvas that displays at 840px instead of 420px on a 2x pixel ration phone.

This would help with clarity on 2x displays and pinch to zoom. 

The current work around is to set the `width: 200%` and then `transform: scale(0.5)`, with the container having `margin-bottom: -100%`

**Comment by FranckFreiburger** [comment]
@rayfoss please give me some feedback about vue-pdf@3.0.2

**Comment by dcean** [comment]
Hello，thanks for your pdf-vue library.

My phone`s resolution ratio is 1920*1080 and my computer is macbook pro. I test my code at them. 

it seems that PDF can`t display when you add code as follows：

```
var devicePixelRatio = window.devicePixelRatio || 1
var pageWidth = viewport.width * devicePixelRatio
var pageHeight = viewport.height * devicePixelRatio

emitEvent('page-size', pageWidth, pageHeight)
canvasElt.width = pageWidth
canvasElt.height = pageHeight
```

when I use code as follows PDF can display but blurry：

```
emitEvent('page-size', viewport.width, viewport.height)
canvasElt.width = viewport.width
canvasElt.height = viewport.height
```

When i use mozilla/pdf.js, the PDF is clear， not as blurry as vue-pdf is.
So maybe your update：3.0.2  had some bugs, please fix it.

Regards

Dcean

**Comment by FranckFreiburger** [comment]
I do not have access to a Retina Display to make tests

**Comment by dcean** [comment]
My related knowledge is finite，i can`t deal with it myself.

Maybe you can try set up `window.devicePixelRatio = 2` in your code, then make tests?
Or we need help from others......

**Comment by FranckFreiburger** [comment]
doc: https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#JavaScript

**Comment by rayfoss** [comment]
@dcean @FranckFreiburger this is an issue relating to differences in vueport sizing vs canvas sizing. You can get the problems to appear even at 125% zoom on desktop.

Problem #1 Page 1 doesn't load (Rendering cancelled exception):
pages don't load reliably, particularly page 1. If page 2 manages to load, it's usually smooth sailing from there. 

How to reproduce:
It happens 100% of the time on the android emulator with a nexus 5 Api 26. Setting page zoom on chrome to 500% on a mac makes it happen reliably for me.

Problem #2 subsequent pages don't load (Cannot use the same canvas during multiple render): 
Looks like a race condition, a big pdf seems to exacerbate it. 

How to reproduce:
I managed to make it show up more reliably on desktop by flipping pages as early as possible. It happens 100% of the time on the android emulator with a nexus 5 Api 26.

Problem #3: 
Pages shrink when viewport is zoomed or using HiDPI/Retina

How to reproduce: zoom in on the page and reload in desktop. Happens 100% on N5 emulator, which has a pixel ratio of 3, some devices have 4, some have half ratios such as 1.5.

**Comment by zjjjjjjjjjjd** [comment]
why close this issue ?This problem occurred in 4.0.8
