### ISSUE TITLE
 ie not supported

### ISSUE THREAD

**Issue by wu617354970** [FranckFreiburger/vue-pdf#223]
ie11 not supported！
The project won't come up .
script1003， Missing semicolon ！

**Comment by kennethrorstromnine** [comment]
Same for me more or less:
SCRIPT1003: Expected ':'

Is IE 11 supported for Vue-PDF ?

**Comment by FranckFreiburger** [comment]
see https://github.com/mozilla/pdf.js/releases/tag/v2.4.456

**Comment by FranckFreiburger** [comment]
should be fixed in v4.0.11 (see https://github.com/FranckFreiburger/vue-pdf/commit/4bf65a45ac1020a4c58bafe074f91ce66397480f)
