### ISSUE TITLE
Doesn't work out-of-the-box

### ISSUE THREAD

**Issue by ThibaultVlacich** [FranckFreiburger/vue-pdf#225]
When installing this, I'm getting this error:

```
   ERROR in ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&)
  Module not found: Error: Can't resolve 'worker-loader' in 'node_modules/vue-pdf/src'
```

Looks like you were using a transient dependency. `pdfjs-dist` had this dependency in the past, but removed it.

**Comment by FranckFreiburger** [comment]
I can add worker-loader as peerDependencies

**Comment by Dimashaman** [comment]
I have the same error,  ThibaultVlacich is right
 `{
  "_from": "pdfjs-dist@^2.4.456",
  "_id": "pdfjs-dist@2.4.456",
  "_inBundle": false,
  "_integrity": "sha512-yckJEHq3F48hcp6wStEpbN9McOj328Ib09UrBlGAKxvN2k+qYPN5iq6TH6jD1C0pso7zTep+g/CKsYgdrQd5QA==",
  "_location": "/pdfjs-dist",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "pdfjs-dist@^2.4.456",
    "name": "pdfjs-dist",
    "escapedName": "pdfjs-dist",
    "rawSpec": "^2.4.456",
    "saveSpec": null,
    "fetchSpec": "^2.4.456"
  },
  "_requiredBy": [
    "/vue-pdf"
  ],
  "_resolved": "https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-2.4.456.tgz",
  "_shasum": "0eaad2906cda866bbb393e79a0e5b4e68bd75520",
  "_spec": "pdfjs-dist@^2.4.456",
  "_where": "/home/www/test.duma-ys.ru/ProjectX/node_modules/vue-pdf",
  "browser": {
    "fs": false,
    "http": false,
    "https": false,
    "url": false,
    "zlib": false
  },
  "bugs": {
    "url": "https://github.com/mozilla/pdf.js/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Generic build of Mozilla's PDF.js library.",
  "format": "amd",
  "homepage": "http://mozilla.github.io/pdf.js/",
  "keywords": [
    "Mozilla",
    "pdf",
    "pdf.js"
  ],
  "license": "Apache-2.0",
  "main": "build/pdf.js",
  "name": "pdfjs-dist",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mozilla/pdfjs-dist.git"
  },
  "version": "2.4.456"
}

`{
  "_from": "pdfjs-dist@^2.3.200",
  "_id": "pdfjs-dist@2.3.200",
  "_inBundle": false,
  "_integrity": "sha512-+8wBjU5h8LPZOIvR9X2uCrp/8xWQG1DRDKMLg5lzGN1qyIAZlYUxA0KQyy12Nw5jN7ozulC6v97PMaDcLgAcFg==",
  "_location": "/pdfjs-dist",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "pdfjs-dist@^2.3.200",
    "name": "pdfjs-dist",
    "escapedName": "pdfjs-dist",
    "rawSpec": "^2.3.200",
    "saveSpec": null,
    "fetchSpec": "^2.3.200"
  },
  "_requiredBy": [
    "/pdfvuer",
    "/vue-pdf"
  ],
  "_resolved": "https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-2.3.200.tgz",
  "_shasum": "2920dc28ae7f2b8313cd6d6223c97ae85ac07eac",
  "_spec": "pdfjs-dist@^2.3.200",
  "_where": "D:\\Oserver\\OSPanel\\domains\\project\\node_modules\\pdfvuer",
  "browser": {
    "fs": false,
    "http": false,
    "https": false,
    "node-ensure": false,
    "zlib": false
  },
  "bugs": {
    "url": "https://github.com/mozilla/pdf.js/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "node-ensure": "^0.0.0",
    "worker-loader": "^2.0.0"
  },
  "deprecated": false,
  "description": "Generic build of Mozilla's PDF.js library.",
  "format": "amd",
  "homepage": "http://mozilla.github.io/pdf.js/",
  "keywords": [
    "Mozilla",
    "pdf",
    "pdf.js"
  ],
  "license": "Apache-2.0",
  "main": "build/pdf.js",
  "name": "pdfjs-dist",
  "peerDependencies": {
    "webpack": "^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mozilla/pdfjs-dist.git"
  },
  "version": "2.3.200"
}
`

**Comment by ThibaultVlacich** [comment]
> 
> 
> I can add worker-loader as peerDependencies

I think it should be a dependency, not a peer dependency. Peer dependencies are to be used when you're extending something, like a plugin (in the case of this plugin, vuejs could be a peer dependency for example). Here it's something that you are using in your code, so it should be a direct dependency imo.

https://nodejs.org/es/blog/npm/peer-dependencies/

**Comment by ahahn95** [comment]
Were you all able to make any progress on this?

**Comment by jlpereira** [comment]
Same problem here, anyone found the solution?

**Comment by ThibaultVlacich** [comment]
The solution is pretty simple, you just need to add `worker-loader`. But this is a temporary workaround, it should be a dependency of this package.

**Comment by jlpereira** [comment]
Yah thanks, already done that but now im getting a different error:

Uncaught ReferenceError: exports is not defined
    at Module../node_modules/pdfjs-dist/lib/web/ui_utils.js (ui_utils.js:50)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (pdf_link_service.js:37)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/vue-pdf/src/pdfjsWrapper.js (pdfjsWrapper.js:1)
    at __webpack_require__ (bootstrap:19)
    at Module.<anonymous> (vuePdfNoSss.vue?8163:5)
    at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (vuePdfNoSss.vue?8163:20)
    at __webpack_require__ (bootstrap:19)
    at Module../node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (vuePdfNoSss.vue?a36a:1)


Probably related with Babel

**Comment by FranckFreiburger** [comment]
Now babel-plugin-syntax-dynamic-import, loader-utils, raw-loader, worker-loader are back to normal dependencies.

**Comment by Dimashaman** [comment]
> Yah thanks, already done that but now im getting a different error:
> 
> Uncaught ReferenceError: exports is not defined
> at Module../node_modules/pdfjs-dist/lib/web/ui_utils.js (ui_utils.js:50)
> at **webpack_require** (bootstrap:19)
> at Object../node_modules/pdfjs-dist/lib/web/pdf_link_service.js (pdf_link_service.js:37)
> at **webpack_require** (bootstrap:19)
> at Module../node_modules/vue-pdf/src/pdfjsWrapper.js (pdfjsWrapper.js:1)
> at **webpack_require** (bootstrap:19)
> at Module. (vuePdfNoSss.vue?8163:5)
> at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (vuePdfNoSss.vue?8163:20)
> at **webpack_require** (bootstrap:19)
> at Module../node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (vuePdfNoSss.vue?a36a:1)
> 
> Probably related with Babel

I had the same errors, had to delete node_modules and clear npm cache --force and npm install and all ok

**Comment by jlpereira** [comment]
Yah, @Dimashaman . but the last version pushed by @FranckFreiburger(btw thanks so much!!) solves the issue :D
