### ISSUE TITLE
Latest update throws a console error getGlobalEventBus is deprecated

### ISSUE THREAD

**Issue by dvago** [FranckFreiburger/vue-pdf#227]
Hi there,

Thanks for sharing and maintaining this package.
I'm currently using `vue-pdf` as dependency of a project and I found out a problem within the last version update.

Within the console log on page load and page change I receive a console.error coming from the `ui_utils` script

`getGlobalEventBus is deprecated, use a manually created EventBus instance instead.`

Please look at the screenshot in attachment:
![Screenshot 2020-06-04 at 12 52 40](https://user-images.githubusercontent.com/5074033/83753494-4ef66d80-a662-11ea-80b9-d161512c63d5.png)

Here the list of info required:
- vue-pdf 4.0.9
- vue 2.6.11
- @vue/cli-service 4.3.1
- Chrome 83.0.4103.61
- OSX 10.15.4

**Comment by wangliqiang1026** [comment]
I also encountered the same problem

**Comment by FranckFreiburger** [comment]
For now, this is just a warning and can be safely ignored

**Comment by FranckFreiburger** [comment]
This should be fixed in v4.0.12
