### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by gassio** [FranckFreiburger/vue-pdf#24]
I am getting an error when using the component.

`Failed to mount component: template or render function not defined.`

**Comment by ismet** [comment]
I'm getting exactly the same error..

**Comment by FranckFreiburger** [comment]
please give more details about your configuration. vue version, webpack version, ... even code sample

**Comment by ismet** [comment]
I am using the same code in your documentation : **Example - complete**.

The package versions are as following;
```
+-- axios@0.16.2
+-- babel-core@6.26.0
+-- babel-loader@7.1.2
+-- babel-preset-env@1.6.0
+-- buefy@0.5.3
+-- cross-env@5.0.5
+-- crypto-js@3.1.9-1
+-- css-loader@0.28.7
+-- file-loader@1.1.5
+-- lodash@4.17.4
+-- moment@2.18.1
+-- style-loader@0.19.0
+-- v-money@0.8.0
+-- vue@2.4.4
+-- vue-js-cookie@2.1.0
+-- vue-loader@13.0.5
+-- vue-pdf@1.2.4
+-- vue-router@2.7.0
+-- vue-template-compiler@2.4.4
+-- webpack@3.6.0
+-- webpack-dev-server@2.9.1
```

**Comment by accardo** [comment]
I'm getting exactly the same error..

**Comment by blitheinsz** [comment]
I'm getting exactly the same error..

**Comment by beerett** [comment]
Getting the same error, the PDF loads, also I'm using the quasar framework.

`<template>
<div> 
     <div v-if="recipe" class="content" :key="recipe.id">      
       <pdf :src=recipe.pdf style="width:75%"></pdf>
      </div> 
</div>
</template>`

**Comment by beerett** [comment]
After countless google searching I wound up editing pdf.vue -- 
It looks related to the way modules are loaded -- I'm fairly new to Vue and ES in general...
I added .default to line 157 and the error is gone, looks like resizing/scaling works as well.
What led me to this [VueJS Changes](https://github.com/vuejs/vue-loader/releases/tag/v13.0.0)
```
var resizeSensor = require('vue-resize-sensor').default;
```

**Comment by FranckFreiburger** [comment]
Thanks for sharing your investigations.
Note that I will use esm only in the next major version of vue-pdf.

**Comment by felisio** [comment]
@FranckFreiburger , When you will generate a new version, fixing this bug? Thanks..

**Comment by FranckFreiburger** [comment]
please check v2.x

**Comment by accardo** [comment]
![image](https://user-images.githubusercontent.com/12389303/32472495-eb1e313e-c39d-11e7-82ad-eeb17fad4622.png)

**Comment by yiyulong** [comment]
Thanks to @beerett, my problem has been solved
