### ISSUE TITLE
Unknown custom element: <pdf> ERROR

### ISSUE THREAD

**Issue by jakub-wisniewski** [FranckFreiburger/vue-pdf#26]
I follow the instructions but I got error in console: 

Unknown custom element: <pdf>

I registered this component in main.js with Vue.component('vue-pdf', pdf) 
but error still appers...

**Comment by FranckFreiburger** [comment]
I can successfully use:
```
import vuePdf from 'vue-pdf'
Vue.component('vue-pdf', vuePdf)
```

**Comment by FranckFreiburger** [comment]
feel free to reopen if the issue still persist

**Comment by xilibro** [comment]
Got the same error

**Comment by xilibro** [comment]
in main.js
`import vuePdf from 'vue-pdf'
Vue.component('vue-pdf', vuePdf)`

int PDFDemo.vue
`
<template>
  <vuePdf src="./static/exportPDF.pdf"></vuePdf>
</template>
`
got error

**Comment by FranckFreiburger** [comment]
Try to replace `<vuePdf>` with `<vue-pdf>`

**Comment by oocar** [comment]
<template>
  <v-pdf src="../../static/doc.pdf"></v-pdf>
</template>

<script>
import VuePDF from 'vue-pdf'

export default {
  components: {
    "v-pdf": VuePDF
  }
}

---> [Vue warn]: Unknown custom element: <v-pdf> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by kosaurang** [comment]
same issue :
main.js : Vue.component("vue-pdf", vuePdf);
page.vue : 

<template>
  <vuePdf src="@/assets/Test.pdf"></vuePdf>
</template>

<script>
import vuePdf from "vue-pdf";

export default {
  
  components: {
    vuePdf
  }

}

**Comment by yfdoor** [comment]
same issue:        
       [Vue warn]: Unknown custom element: <pdf> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
