### ISSUE TITLE
vue-pdf 3.0 not support

### ISSUE THREAD

**Issue by leafront** [FranckFreiburger/vue-pdf#269]
Uncaught (in promise) TypeError: h is not a function
Proxy.render (componentFactory.js?4fc9:16)

**Comment by MFRamon** [comment]
have you found a workaround to make this work?

**Comment by macmanpb** [comment]
I have the same issue with a ionic/Vue PWA App. Vue: 3 and Ionic: 5.

**Comment by ashafizullah** [comment]
I have the same issue too with Ionic.

**Comment by leafront** [comment]
> have you found a workaround to make this work?

No, use Vue 2.0

**Comment by leafront** [comment]
> I have the same issue with a ionic/Vue PWA App. Vue: 3 and Ionic: 5.

No, use Vue 2.0

**Comment by leafront** [comment]
> I have the same issue too with Ionic.

No, use Vue 2.0

**Comment by leafront** [comment]
npm install vue3-pdf --save-dev
