### ISSUE TITLE
JSFiddle demo not working

### ISSUE THREAD

**Issue by Omnipresent** [FranckFreiburger/vue-pdf#27]
I tried the jsfiddle demo but it isn't working: https://jsfiddle.net/9zm9c1sf/24/

Is there another jsfiddle that shows this in action?

**Comment by Omnipresent** [comment]
Hi @FranckFreiburger - Can you please let me know what might be wrong with the example fiddle? I can help fix it and send a PR if needed.

**Comment by DomenicRoti** [comment]
I'm having a similar problem when I try to load files from external sources...I'm curious if that's what the problem with the fiddle is.  Also I'm not sure if it's related, but I see the progress event always returns NaN

**Comment by FranckFreiburger** [comment]
Now that vue-pdf@2.x use esm, I cannot use fiddle any more.
I plan to release a cjs version.
Meanwhile I can use an old vue-pdf@1.x version for the fiddle demo ...

**Comment by rayfoss** [comment]
https://jsfiddle.net/fossfiddler/5k4ptmqg/126/
I couldn't get numPages to work though

working version manually included and stripped of incompatibilities. Perhaps it would be easier to use github pages?

**Comment by rayfoss** [comment]
Alright, this one is working... don't know why the num pages isn't updating
The sources are pulled from 3.2

https://jsfiddle.net/fossfiddler/5k4ptmqg/138/
