### ISSUE TITLE
tips font error

### ISSUE THREAD

**Issue by weihongyu12** [FranckFreiburger/vue-pdf#29]
I was prompted to a mistake when loading PDF, seems to be caused by the font, I use Chinese fonts here, how should I set it?

Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked").

**Comment by FranckFreiburger** [comment]
Please try to open your file with http://mozilla.github.io/pdf.js/web/viewer.html?file=

**Comment by weihongyu12** [comment]
Yes, my file can be opened at this site, but if I can not load the web using the component, the text will not be displayed at the time of printing

**Comment by FranckFreiburger** [comment]
Can you provide a pdf file with Chinese fonts ?

**Comment by weihongyu12** [comment]
@FranckFreiburger [test.pdf](https://github.com/FranckFreiburger/vue-pdf/files/1620976/test.pdf)

**Comment by FranckFreiburger** [comment]
please try v3.1.6+

**Comment by FranckFreiburger** [comment]
ping !

**Comment by FranckFreiburger** [comment]
please re-open if it is still outstanding

**Comment by mxcmm** [comment]
I have the same problem with 3.2.2. When I use 3.1.6, NPM will report errors. version of Vue is 2.5.7.

**Comment by mxcmm** [comment]
@FranckFreiburger thank you, the file like weihongyu12's.

**Comment by fanGuangqing** [comment]
@FranckFreiburger  hello，I was prompted to a mistake when loading PDF,I use Chinese fonts here,how should I set it?

Warning: Unimplemented annotation type "BJCA:Annot", falling back to base annotation.
Warning: Error during font loading: The CMap "baseUrl" parameter must be specified, ensure that the "cMapUrl" and "cMapPacked" API parameters are provided.
I hope you can help me
