### ISSUE TITLE
当前pdf未全部加载完成关闭后，后续pdf无法渲染问题

### ISSUE THREAD

**Issue by dali-web** [FranckFreiburger/vue-pdf#294]
当前pdf未全部加载完成关闭后，后续pdf无法渲染问题

**Comment by JiaLiBai** [comment]
在 node_modules⁩/vue-pdf⁩/⁨src⁩/pdfjsWrapper.js  找到renderPage函数  
 
在pendingOperation = pendingOperation.then(function ()....bind(this));前面加上  if(pdfDoc)

**Comment by zoubeihua** [comment]
有没有加载完成回调呢？pdf加载的时候加一个loding
