### ISSUE TITLE
Warning: Setting up fake worker

### ISSUE THREAD

**Issue by skallio** [FranckFreiburger/vue-pdf#3]
When opening the pdf view the first time, the browser console shows disturbing warnings and messages:

pdf.js?013a:2840 GET http://localhost:8080/app.worker.js PDFWorker_initialize @ pdf.js?013a:2840PDFWorker @ pdf.js?013a:2813getDocument @ pdf.js?013a:2264PDFJSWrapper.loadDocument @ pdf.vue?997e:386mounted @ pdf.vue?997e:501callHook @ vue.common.js?e881:2534insert @ vue.common.js?e881:3361invokeInsertHook @ vue.common.js?e881:5179patch @ vue.common.js?e881:5343Vue._update @ vue.common.js?e881:2301updateComponent @ vue.common.js?e881:2417get @ vue.common.js?e881:2756run @ vue.common.js?e881:2826flushSchedulerQueue @ vue.common.js?e881:2593(anonymous function) @ vue.common.js?e881:654nextTickHandler @ vue.common.js?e881:601
pdf.js?013a:344 Warning: Setting up fake worker.
pdf.worker.js?1385:24096The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

**Comment by FranckFreiburger** [comment]
The first is just a warning to inform you that pdfjs will use the fake worker. The second warning is displayed during feature detection. Both does not indicate any sort of error.
I am working on a better integration of pdfjs web worker.

BTW, what is the browser ? are you using webpack ?

**Comment by skallio** [comment]
Webpack yes, and the warning about fake worker occur at least on Chrome and Firefox.

Is it possible to get rid of the warning?

**Comment by FranckFreiburger** [comment]
Please update to the latest version. The warning should disappear.

**Comment by skallio** [comment]
Thank you!

**Comment by skallio** [comment]
Actually, still this warning remains at least on chrome.
pdf.worker.js:24096The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.

Is it possible to remove this also?

**Comment by FranckFreiburger** [comment]
Sorry, this warning cannot be removed without changing the pdf.js source code.
