### ISSUE TITLE
Multiple renders error

### ISSUE THREAD

**Issue by danjesus** [FranckFreiburger/vue-pdf#306]
Hi,

I am trying to render two pages simultaneously, but at any moment most of them do not load and I have the problem with multiple renders running at the same time.

Is there a way to correct this behavior?

By the way, how was this issue resolved here? https://github.com/mozilla/pdf.js/issues/10018

**Comment by danjesus** [comment]
Hello I fix this error usings v-for to load more than one page.

**Comment by hjw5744s** [comment]
Hi I would like to see the resolved code.
