### ISSUE TITLE
Src/Data accepting base64 input

### ISSUE THREAD

**Issue by jeden1974** [FranckFreiburger/vue-pdf#31]
Hi,
Great lib many thanks.

I'm getting a base 64 stream of a PDF from my API.  I tried getting the data input working but that failed so looking at the source for pdf.js it seems that using an ArrayBuffer on the src input allows this.  I got it working fine however I end up with a Vue warning in the console saying about data types.  The pdf displays but there is the warning.

To fix it I modified the source to change the src props, line 441, I added ArrayBuffer to the permitted types.  Now no warning.

Could that be added to the code please?

Also did you intend doing any code for zooming ?

Regards

Jon

**Comment by andreasvirkus** [comment]
Would also like to see support for zooming

**Comment by FranckFreiburger** [comment]
TypedArray and base64 are supported by PDFJS, therefore by vue-pdf:
```
	<pdf :src="pdfSrc"></pdf>
...
	data() {
		return {
			pdfSrc: { data: typedArray }
		}
	},
```

For base64, you should use:
`<pdf :src="'data:application/pdf;base64,' + yourBase64Data"></pdf>`

**Comment by jeden1974** [comment]
Apologies - only just saw this and it works great - thanks very much,

Jon

**Comment by pathikmehta** [comment]
@FranckFreiburger This is not working for me. I am using `4.1.0` version of vue-pdf. 
`<pdf :src="'data:application/pdf;base64,' + yourBase64Data"></pdf>`

If I use simple `iframe` like this it works but having other issues with iframe.
`<iframe :src="'data:application/pdf;base64,' + yourBase64Data" />`
