### ISSUE TITLE
Module not found: Error: Can't resolve 'pdfjs-dist/es5/build/pdf.js' in '/app/node_modules/vue-pdf/src'

### ISSUE THREAD

**Issue by Ashwanth-kumar** [FranckFreiburger/vue-pdf#315]
**Hi Team... Can anyone please help me.. i'm facing the error in vue-pdf**

**"vue": "^2.6.12",
"vue-pdf": "^4.2.0",
"webpack: "^4.44.2"**

ERROR in ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'pdfjs-dist/es5/build/pdf.js' in '/app/node_modules/vue-pdf/src'
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&) 7:14-52
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue
@ ./src/app.js
@ multi ./src/app.js

ERROR in ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'pdfjs-dist/es5/build/pdf.worker.js' in '/app/node_modules/vue-pdf/src'
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&) 10:22-81
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue
@ ./src/app.js
@ multi ./src/app.js

ERROR in ./node_modules/vue-pdf/src/pdfjsWrapper.js
Module not found: Error: Can't resolve 'pdfjs-dist/es5/web/pdf_viewer' in '/app/node_modules/vue-pdf/src'
@ ./node_modules/vue-pdf/src/pdfjsWrapper.js 1:0-63 157:28-42
@ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js&
@ ./node_modules/vue-pdf/src/vuePdfNoSss.vue
@ ./src/app.js
@ multi ./src/app.js

@FranckFreiburger

**Comment by Ilshidur** [comment]
I fixed it by changing this in my `package-lock.json` file :

```diff
- "pdfjs-dist": {
-   "version": "2.8.335",
-   "resolved": "https://npm.cloudsystem.fr/pdfjs-dist/-/pdfjs-dist-2.8.335.tgz",
-   "integrity": "sha512-2IKw7wP1RnzzWJcpkeZwF+cKROFiQext+/WburB6cgKwt9zc8rOyDH7a3FepdcciSGs8SDs/AuWe8qVx+iI6pw=="
- },
+ "pdfjs-dist": {
+   "version": "2.7.570",
+   "resolved": "https://npm.cloudsystem.fr/pdfjs-dist/-/pdfjs-dist-2.7.570.tgz",
+   "integrity": "sha512-/ZkA1FwkEOyDaq11JhMLazdwQAA0F9uwrP7h/1L9Akt9KWh1G5/tkzS+bPuUELq2s2GDFnaT+kooN/aSjT7DXQ=="
+ },
```

Then I ran `npm ci`.

Please note that this will be erased if you happen to run `npm install` again. I hope it helps.

**Comment by EHadoux** [comment]
Looks like it's related to https://github.com/mozilla/pdf.js/pull/12978.

**Comment by Ashwanth-kumar** [comment]
> I fixed it by changing this in my `package-lock.json` file :
> 
> ```diff
> - "pdfjs-dist": {
> -   "version": "2.8.335",
> -   "resolved": "https://npm.cloudsystem.fr/pdfjs-dist/-/pdfjs-dist-2.8.335.tgz",
> -   "integrity": "sha512-2IKw7wP1RnzzWJcpkeZwF+cKROFiQext+/WburB6cgKwt9zc8rOyDH7a3FepdcciSGs8SDs/AuWe8qVx+iI6pw=="
> - },
> + "pdfjs-dist": {
> +   "version": "2.7.570",
> +   "resolved": "https://npm.cloudsystem.fr/pdfjs-dist/-/pdfjs-dist-2.7.570.tgz",
> +   "integrity": "sha512-/ZkA1FwkEOyDaq11JhMLazdwQAA0F9uwrP7h/1L9Akt9KWh1G5/tkzS+bPuUELq2s2GDFnaT+kooN/aSjT7DXQ=="
> + },
> ```
> 
> Then I ran `npm ci`.
> 
> Please note that this will be erased if you happen to run `npm install` again. I hope it helps.

Thanks for Replying :)  This seems to be a temporary fix for local environment. My app is in deployment there this won't work i guess

**Comment by Ashwanth-kumar** [comment]
> Can author fix it? @FranckFreiburger

Yes...I'm hoping @FranckFreiburger will look into this

**Comment by alex-eri** [comment]
#313 for quick fix.

`yarn add pdfjs-dist@2.7.570` for workaround

**Comment by Ashwanth-kumar** [comment]
> #313 for quick fix. But needed more work for upgrade.
> 
> `yarn add pdfjs-dist@2.7.570` or `npm install pdfjs-dist@2.7.570` in project for workaround. It helps with package-lock.json rewrite problem.

Thanks @alex-eri,It is working after installing pdfjs-dist@2.7.570

**Comment by Dhruti-TerminalTrend** [comment]
> npm install pdfjs-dist@2.7.570

Thanx @alex-eri. It is working
