### ISSUE TITLE
我如何可以原样输出显示展示出原来pdf的宽高

### ISSUE THREAD

**Issue by ypinchina** [FranckFreiburger/vue-pdf#318]
我不想要pdf的显示随着div的改变大小而改变，我如何让pdf像原样大小的宽高渲染出来，或者如何获取原来pdf文件的宽高？

**Comment by abdulmlik** [comment]
try this 
`
<div class="pdf-content" >
      <div  class="pdf-viewer-wrapper">
          <pdf
            :src="pathSrc"
            :page="1"
            :style="`width:800px`"
          ></pdf>
        </div>

<style lang="scss" >
.pdf-content {
  overflow: hidden;
  height: 100%;
  position: relative;
  .pdf-viewer-wrapper {
    overflow: auto;
    position: relative;
    height: 100%;
  }
}
</style>
`

**Comment by ypinchina** [comment]
> ```
> :style="`width:800px`"
> ```

thanks sir, but it means if original width and height of my pdf isn't 800px ,  how can i due it.

**Comment by ypinchina** [comment]
我希望vue-pdf能渲染出原来pdf的大小 ，而不会是让pdf的渲染随着我的container 或者 说容器的宽度变大 而变大，我该如何code?

**Comment by ypinchina** [comment]
> try this
> 
> ```
> <div class="pdf-content" >
>       <div  class="pdf-viewer-wrapper">
>           <pdf
>             :src="pathSrc"
>             :page="1"
>             :style="`width:800px`"
>           ></pdf>
>         </div>
> </div>
> 
> <style lang="scss">
> .pdf-content {
>   overflow: hidden;
>   height: 100%;
>   position: relative;
>   .pdf-viewer-wrapper {
>     overflow: auto;
>     position: relative;
>     height: 100%;
>   }
> }
> </style>
> ```
thanks sir, but it means if original width and height of my pdf isn't 800px , how can i due it.我希望vue-pdf能渲染出原来pdf的大小 ，而不会是让pdf的渲染随着我的container 或者 说容器的宽度变大 而变大，我该如何code?

**Comment by liujk-tj** [comment]
修改pdfjsWrapper.js，this.loadPage里获取信息pdf.getViewport({ scale: 1 })，@page-loaded回调里返回pdf的宽度和高度信息
