### ISSUE TITLE
PDF.js allow src to be ArrayBuffer or Uint8Array, so should your src property

### ISSUE THREAD

**Issue by glacjay** [FranckFreiburger/vue-pdf#33]
otherwise there will be an vue warn.

**Comment by achimkoellner** [comment]
I need to load pdf-files from a local device file storage using the file:// protocol in a corcova environment.
I get the MissingPDFException (thrown in pdf.js) obviously the file:// protocol is not supported by pdf.js so the the only chance I have would be to use an ArrayBuffer or Uint8Array as src (which is not yet supported), am I right?

**Comment by arkokoley** [comment]
@achimkoellner It was supported in the versions before 2.0, I had been using it in my projects. Just use the v.1.25 and send a Uint8Array as src.

**Comment by FranckFreiburger** [comment]
According to the PDFJS inlined documentation, `TypedArray` is supported: https://github.com/mozilla/pdf.js/blob/6b2ed504b7b11cfc1060bf9860db78d628c9a3ed/src/display/api.js#L100

**example:**
```
<pdf :src="pdfSrc"></pdf>
```
where pdfSrc = { data: myTypedArray }
