### ISSUE TITLE
If I use S3 link CORS error is blocking what to do

### ISSUE THREAD

**Issue by tausif7851** [FranckFreiburger/vue-pdf#347]

**Comment by a-di-ez** [comment]
@tausif7851 add this to s3 bucket => Permissions => CORS => Edit

[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "HEAD",
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]

**Comment by tausif7851** [comment]
Thanks it worked but need to add * inside double quotes
