### ISSUE TITLE
I met a very headache problem, i need your help !!!

### ISSUE THREAD

**Issue by Keecat** [FranckFreiburger/vue-pdf#39]
In just, my project suddenly report error with Error in mounted hook: "TypeError: Cannot read property 'setProp' of undefined" found in vue-pdf.vue...  I don't know what to do now, Wait for your reply。 >﹏< ... 
![i18u9_78w1k5 2darxf 1s](https://user-images.githubusercontent.com/20496148/34477118-2ecf3ac6-efd2-11e7-9799-c44279128151.png)

**Comment by arkokoley** [comment]
:+1: Same issue in #36 

@FranckFreiburger any ideas?

**Comment by FranckFreiburger** [comment]
duplicate with https://github.com/FranckFreiburger/vue-pdf/issues/37
