### ISSUE TITLE
Error in mounted hook: "TypeError: Cannot read property 'setProp' of undefined"

### ISSUE THREAD

**Issue by laolao114** [FranckFreiburger/vue-pdf#41]
Sorry for disturbing you, but it appears and annoys me. After update the lastest version, the console report this,
' Error in mounted hook: "TypeError: Cannot read property 'setProp' of undefined"

found in', 
'Error in event handler for "resize": "TypeError: Cannot read property 'getResolutionScale' of undefined',
What should I do? I use npm

**Comment by FranckFreiburger** [comment]
I need more details:
- browser name & version
- vue.js version
- vue-pdf version

**Comment by Keecat** [comment]
I have the same problem，vue version:2.5.9, vue-pdf version: 2.0.4. I think it should be the version of webpack（webpack-dev-server...） in Vue-cli。by the time, I didn't solve this problem.

**Comment by laolao114** [comment]
I had solved it by delete node_modules and rerun the project. I think the cache affected it

**Comment by FranckFreiburger** [comment]
Feel free to reopen the issue if the problem is still present.
