### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by jiang-xiche** [FranckFreiburger/vue-pdf#42]
![image](https://user-images.githubusercontent.com/26916168/34637541-de254f14-f2f3-11e7-8b37-af324d20a00f.png)

what should i do?

**Comment by FranckFreiburger** [comment]
please give more details

**Comment by jiang-xiche** [comment]
My current version of webpack is 1.13.2 = =

**Comment by FranckFreiburger** [comment]
please try with the latest version of webpack

**Comment by jiang-xiche** [comment]
now is ok thanks :)
