### ISSUE TITLE
report error with 'TypeError: Cannot read property 'setProp' of undefined'

### ISSUE THREAD

**Issue by Keecat** [FranckFreiburger/vue-pdf#44]
before, ther webpack version is 2.6.1 in vue-cli, the vue-pdf version is 1.2.4, there is no problem. but now, report error. I deleted the relevant code width 'setProp' in vue-pdf.vue. It's not wrong. But it's too much trouble.  I have some pictures, you can look at it. (I hope you can solve this problem quickly.)

![a ck j 9 j c j2am7](https://user-images.githubusercontent.com/20496148/34661966-2dc40ec6-f488-11e7-806a-2bd71cc7280e.png)
![jj 3 x 5 ts_ya5 6t3 9e](https://user-images.githubusercontent.com/20496148/34661967-2ea128c4-f488-11e7-93c5-7018d2d20313.png)
![ci czzkx j o1gcg 3jmo](https://user-images.githubusercontent.com/20496148/34661971-315154cc-f488-11e7-8375-f85b737704b5.png)

**Comment by FranckFreiburger** [comment]
`setProp` issue has been fixed in vue-pdf 3.0.0 (see https://github.com/FranckFreiburger/vue-pdf/commit/3e27440b277bbf4afacd3255430d200fbbf157cb)

and I don't understand why `getResolutionScale` is called against undefined in method `resize()`

**Comment by FranckFreiburger** [comment]
please try the latest vue-pdf (v3.x.x)

**Comment by Keecat** [comment]
@sorry I had not noticed, you finally got back to me. ha ha ha @

**Comment by FranckFreiburger** [comment]
feel free to reopen if needed
