### ISSUE TITLE
Only first instance of PDF is rendered when using Element-UI

### ISSUE THREAD

**Issue by jeffcann** [FranckFreiburger/vue-pdf#5]
Multiple PDFs do not work with Element-UI versions later than 1.0.0-rc5.

[Working](https://jsfiddle.net/9zm9c1sf/28/) with element-ui 1.0.0-rc5
[Not working](https://jsfiddle.net/9zm9c1sf/27/) with element-ui 1.0.0-rc6

**Comment by Mmpc1994** [comment]
i have the question, too !

**Comment by FranckFreiburger** [comment]
please can you tell me if the issue is still present with Element-UI v2.x ?

**Comment by FranckFreiburger** [comment]
fixed using Element-UI versions  2.0.10
