### ISSUE TITLE
@num-pages and @page-loaded listeners aren't working

### ISSUE THREAD

**Issue by noahduncan** [FranckFreiburger/vue-pdf#50]
I think this is probably an issue with newer versions of Vue.js.  In order to listen to emitted events for num-pages and page-loaded I need to use @numPages and @pageLoaded.

I'm using Vue 2.5.3.

**Comment by FranckFreiburger** [comment]
events should be @page-loaded and @num-pages.
eg.
`<pdf @num-pages="numPages = $event"></pdf>`

**Comment by FranckFreiburger** [comment]
Feel free to reopen if the problem persists.
