### ISSUE TITLE
Webpack production build fails with UglifyJS error

### ISSUE THREAD

**Issue by andreasg** [FranckFreiburger/vue-pdf#53]
Steps to reproduce

`$ vue init webpack test`

Complete steps. (Using standalone build and npm.)

```
$ cd test
$ npm install -S vue-pdf
```

Add 
`import pdf from 'vue-pdf'`
to `src/main.js`

Build with minimization enabled
`$ ./node_modules/.bin/webpack -p --config build/webpack.prod.conf.js`

Observe UglifyJS error:

```
ERROR in static/js/app.6700a7c5602062172c87.js from UglifyJs
Unexpected token: punc (() [node_modules/vue-pdf/src/pdf.vue:487,0][static/js/app.6700a7c5602062172c87.js:1,23252]
```

I'm far from an expert on webpack and related tooling such as babel, and frankly I have no idea why this happens.

**Comment by jeden1974** [comment]
I had a similar error and had to revert to 3.0.0.  In my case the createLoadingTask introduction caused this - I think that uglifyjs didn't like the way it was added to the export...

**Comment by danielprogramic** [comment]
Hello, I had the same problem 
I installed the version 3.0.0 of vue-pdf
Thanks!!@!

**Comment by wskongdesheng** [comment]
Hello, Me too with the same problem
I installed the version 3.1.2
Thanks!!!

**Comment by FranckFreiburger** [comment]
Unexpected token: punc (() ... is related to UglifyJS es6 support. (note that the latest uglifyjs-webpack-plugin supports es6 syntax).
Please try v3.1.3

**Comment by jeden1974** [comment]
Thanks Franck, that resolved it :)

**Comment by andreasg** [comment]
Thank you @FranckFreiburger works for me now
