### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by jeden1974** [FranckFreiburger/vue-pdf#54]
Hi Franck,

Re the zoom functionality seen in the main pdf.js demo (https://mozilla.github.io/pdf.js/web/viewer.html).  

Can vue-pdf currently use that functionality or am I mistaken in thinking that currently it doesn't.

Assuming that it doesn't do you have any plans on when it will be integrated or ideas on how I could implement it myself?

Regards

Jon

**Comment by FranckFreiburger** [comment]
please look at issue https://github.com/FranckFreiburger/vue-pdf/issues/15

**Comment by jeden1974** [comment]
Thanks Franck,  Looks like that does the trick - now to have a play with the container divs to get it scrolling properly :)
