### ISSUE TITLE
Pdfjs-dist size

### ISSUE THREAD

**Issue by andreasvirkus** [FranckFreiburger/vue-pdf#56]
Babel loader reports the newer version of `pdfjs-dist` (`pdfjs-dist@2.0.310`) to be incredibly large, making all builds and dev runtime very, *very* slow (adding ~5-10min per build/rebuild). Issue didn't seem to be present on `pdfjs-dist@2.0.303`, what were the major benefits of upgrading and would it be possible to revert?

```
[BABEL] Note: The code generator has deoptimised the styling of 
"/Users/andreas.virkus/code/sweden-loan-application/node_modules/pdfjs-dist/build/pdf.js"
as it exceeds the max of "500KB".
```

**Comment by andreasvirkus** [comment]
Letting the Webpack build finish to measure the total build time:
```
[BABEL] Note: The code generator has deoptimised the styling of "/project/node_modules/pdfjs-dist/build/pdf.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/project/node_modules/pdfjs-dist/build/pdf.worker.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/project/node_modules/pdfjs-dist/build/pdf.worker.js" as it exceeds the max of "500KB".
webpack built 5b72440a745a09800f82 in 670019ms
```

**Comment by FranckFreiburger** [comment]
Please confirm that this issue appeared between pdfjs-dist@2.0.303 and pdfjs-dist@2.0.310

**Comment by andreasvirkus** [comment]
Sorry for the seemingly dumb question, but how can I test that? Changing `pdfjs-dist` version in my `package-lock`?

**Comment by andreasvirkus** [comment]
Issue is still there with latest version (`pdfjs-dist@2.0.334`) 😕  
Also tested with `pdfjs-dist@2.0.303` again and the warnings are still there, but webpack builds a lot quicker (although I now get a warning about raw-loader not being solved):

```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/andreas.v
irkus/code/sweden-loan-application/node_modules/vue-pdf/node_modules/pdfjs-dist/b
uild/pdf.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/andreas.v
irkus/code/sweden-loan-application/node_modules/vue-pdf/node_modules/pdfjs-dist/b
uild/pdf.worker.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/andreas.v
irkus/code/sweden-loan-application/node_modules/vue-pdf/node_modules/pdfjs-dist/b
uild/pdf.worker.js" as it exceeds the max of "500KB".
webpack built 204bcd49597493cd0b08 in 34811ms
Hash: 204bcd49597493cd0b08
Version: webpack 3.10.0
Time: 34811ms


ERROR in ./node_modules/vue-pdf/src/pdfjsWrapper.js
Module not found: Error: Can't resolve 'raw-loader' in '/code/node_modules/vue-pdf/src'
 @ ./node_modules/vue-pdf/src/pdfjsWrapper.js 20:11-120
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./node_modules/vue-pdf/src/vuePdfNoSss.vue
 @ ./node_modules/vue-pdf/src/vuePdfNoSss.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./client/src/steps/Signing.vue
 @ ./client/src/steps/Signing.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./client/src/App.vue
 @ ./client/src/App.vue
 @ ./client/src/main.js
 @ multi webpack-hot-middleware/client ./client/src/main.js
```

**Comment by FranckFreiburger** [comment]
1/ does this answer help you: https://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e
2/ check that `raw-loader` is properly installed in `node_modules`

**Comment by andreasvirkus** [comment]
1) Yes, thanks! Sorry, seems that was an issue on my side all along then.
2) No, `raw-loader` is not installed. But when I check `vue-pdf`'s `package.json` then `raw-loader` is listed as a dev dependency. Shouldn't it be under `dependencies`?

**Comment by FranckFreiburger** [comment]
> (Should 2 be converted to a separate issue and this one closed?)
Yes, thanks.

**Comment by FranckFreiburger** [comment]
BTW, check https://github.com/babel/babel-loader#babel-loader-is-slow to speed-up babel
