### ISSUE TITLE
raw-loader missing as a dependency

### ISSUE THREAD

**Issue by andreasvirkus** [FranckFreiburger/vue-pdf#57]
On `3.2.0` I get the following error:
```
ERROR in ./node_modules/vue-pdf/src/pdfjsWrapper.js
Module not found: Error: Can't resolve 'raw-loader' in '/code/node_modules/vue-pdf/src'
 @ ./node_modules/vue-pdf/src/pdfjsWrapper.js 20:11-120
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./node_modules/vue-pdf/src/vuePdfNoSss.vue
 @ ./node_modules/vue-pdf/src/vuePdfNoSss.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./client/src/steps/Signing.vue
 @ ./client/src/steps/Signing.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type
=script&index=0!./client/src/App.vue
 @ ./client/src/App.vue
 @ ./client/src/main.js
 @ multi webpack-hot-middleware/client ./client/src/main.js
```

`raw-loader` also isn't installed in my `node_modules`. But when I check `vue-pdf`'s package.json then `raw-loader` is listed as a dev dependency. Should it be under `dependencies`?

**Comment by FranckFreiburger** [comment]
since `raw-loader` has been added after your initial install, try `npm install`

**Comment by andreasvirkus** [comment]
I shouldn't explicitly visit the `vue-pdf` package dir to install its `devDependencies` there... everything necessary for a package to run/be used should be listed under `dependencies` and therefore installed with the initial `npm install`. Please see my PR https://github.com/FranckFreiburger/vue-pdf/pull/58

**Comment by andreasvirkus** [comment]
Didn't mean to close this (happened when I accidentally created the PR to my own fork's master)...
