### ISSUE TITLE
Only first page rendered on narrower viewports

### ISSUE THREAD

**Issue by andreasvirkus** [FranckFreiburger/vue-pdf#59]
Only the first page is rendered for me with `3.2.0`. Not only on mobile devices,
but also on Chrome's responsive view on desktop (no helpful errors in console though).

![screen shot 2018-02-07 at 12 05 11](https://user-images.githubusercontent.com/9140811/35910465-4bbc3370-0bff-11e8-86a2-edf51c0ce63e.png)

But it renders okay when loading the pdf in a larger viewport and then resizing/switching to responsive mode (although rasterization/resize breaks):

![screen shot 2018-02-07 at 12 15 08](https://user-images.githubusercontent.com/9140811/35910827-92226cd4-0c00-11e8-8fbc-643ab5495d85.png)

**Comment by FranckFreiburger** [comment]
Note that you can use `@error` event on `<pdf>` to see potential errors

**Comment by andreasvirkus** [comment]
Ah, good to know! It logs:
```
(7)
error:: Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
    at InternalRenderTask_initializeGraphics [as initializeGraphics] (pdf.js?9caa:4615)
    at eval (pdf.js?9caa:3605)
    at <anonymous>
```

**Comment by FranckFreiburger** [comment]
FYI, https://github.com/mozilla/pdf.js/issues/9456
