### ISSUE TITLE
Vue-pdf create 168 excess bundles in webpack

### ISSUE THREAD

**Issue by Ascold2017** [FranckFreiburger/vue-pdf#62]
Hello. I'm try import vue-pdf in weback-simple vue template (standart config). And after compile - webpack create my 2 bundles (style.bundle and entry.bundle) and yet 168 bundles. Its only with vue-pdf, i`m try remove vue-pdf and compile - webpack compile only my 2 bundles. With vue-pdf - +168 bundles, like adobe, noprefetch-CNS2-H-bcmap and others. Where are look the problem?
Screen of terminal (my bundles and other)^
![image](https://user-images.githubusercontent.com/29858671/36393465-603244e4-15b8-11e8-885c-f8b82876b8f1.png)

**Comment by FranckFreiburger** [comment]
This behavior is expected. These 168 bcmap files are compiled by webpack and ready to be loaded on demand, only if required by the pdf file.

**Comment by GergelyLakatos** [comment]
Hi!

I use this lib in laravel project. Now my laravel-mix ( = webpack) packs all the js files to _public/js/_ folder. But this lib (when I e.g.: run _npm run dev_) override my _public/mix-manifest.json_ and generate all the new bundles to my _public_ folder.
So some rookie questions come up:
1. Where can I told the lib, where should this "extra" js go?
2. Are these new js files necessary? The prev versions did not do this "mess".
3. What is the last version what's behavior is not like this?

Thanks for the responses in advance. :)

**Comment by guillecro** [comment]
@GergelyLakatos same thing is happening to me

**Comment by GergelyLakatos** [comment]
@guillecro My temp solution is using prev version:   `"vue-pdf": "3.1.0`. This version is working well, and not generate this mess. ;)

**Comment by FranckFreiburger** [comment]
@GergelyLakatos: bcmap files are mandatory in order to display pdf properly (at least to display pdfs with East Asian texts that were created by legacy pdf creation tools).
Feel free to create a new feature request to make this configurable.

**Comment by bostinait** [comment]
@FranckFreiburger Is there anyway to specify where the js gets compiled to, like @GergelyLakatos I am also using Laravel (and laravel mix) so being able to add them to public/js would make it tidier.

Many thanks in advance.

**Comment by GergelyLakatos** [comment]
@bostinait I Use the prev version, it works well. ;)
