### ISSUE TITLE
Display pdf from local device storage (file:// protocol)

### ISSUE THREAD

**Issue by vini23hot** [FranckFreiburger/vue-pdf#64]
Vue-PDF version: 3.2.2
Vue version: 2.5.13
Webpack version: 3.11.0
Quasar Framework version: 0.14.9
Cordova version: 8.0.0

I'm using vue-pdf with Vue.js, Quasar Framework and Cordova to build a mobile app. I used Cordova File plugin and Cordova File-Transfer plugin to download PDF from my Firebase Storage and save in local device storage. 
The URL of PDF downloaded returned by Cordova File-Transfer is `file:///data/user/0/io.cordova.hellocordova/files/livros/Iracema.pdf`, but if i put this URL in :src <pdf> component (Example: `<pdf :src="file:///data/user/0/io.cordova.hellocordova/files/livros/Iracema.pdf" :page="currentPage" @num-pages="pageCount = $event" @loaded="ativar_zoom(), sync_atual()" @error="error"></pdf>`) it doesn't work and return this error in console: `Fetch API cannot load file:///data/user/0/io.cordova.hellocordova/files/livros/Iracema.pdf. URL scheme "file" is not supported.`

How can i display the PDF downloaded with vue-pdf?

**Comment by FranckFreiburger** [comment]
You should try to load you pdf file through webpack file-loader.
untested:
`<pdf :src="require('file-loader!file:///data/user/0/io.cordova.hellocordova/files/livros/Iracema.pdf"  ...`
(I dont know if file-loader supports file://  URL scheme, mayby you will need to use an ansolute or relative silesystem path)

**Comment by vini23hot** [comment]
Thanks for reply! I will test _Webpack File-Loader_ with _vue-pdf_ soon, but i resolved my problem using a **.txt stored in file://**, which content is a **Base64 PDF**, and put the content of file on `:src` tag.

`<pdf :src="'data:application/pdf;base64,' + ContentOfTxtFile"></pdf>`
