### ISSUE TITLE
Need "Print the whole document" feature

### ISSUE THREAD

**Issue by gwwnha** [FranckFreiburger/vue-pdf#7]
Do you have some advice?

**Comment by FranckFreiburger** [comment]
What a strange idea to print a whole document ! :)

**Comment by FranckFreiburger** [comment]
This is an experimental feature:
`printPage(dpi, pageNumberOnly)`
eg. `printPage(100, [1,2,3,4,5,6,7,8])`

**Comment by FranckFreiburger** [comment]
ping !

**Comment by philefstat** [comment]
@FranckFreiburger is printPage supported in the latest npm release?

**Comment by FranckFreiburger** [comment]
yes, it should be supported

**Comment by philefstat** [comment]
Weird... I just checked I am on the latest version (1.2.2) and I can only see the print function, not printPage. When I pass it an array of the 14 pages in the pdf (I am using https://cdn.mozilla.net/pdfjs/tracemonkey.pdf) it only passes 3 pages to the printing prompt. Any ideas?

**Comment by FranckFreiburger** [comment]
it's hardcoded !

```
print: function() {
	
	this.pdf.printPage(100, [1,2,3]);
}
```
you have to print only page 1, 2 and 3 :smile: 

... I will fix it

**Comment by philefstat** [comment]
thanks! I appreciate it.

**Comment by FranckFreiburger** [comment]
it should be fixed, try v1.2.3

**Comment by philefstat** [comment]
yep, it's working now 👍 

Thanks!
