### ISSUE TITLE
Fails to render on high-resolution screens

### ISSUE THREAD

**Issue by markhalonen** [FranckFreiburger/vue-pdf#73]
__vue-pdf version__: 3.2.2
__vue.js version__: 2.5.16
__webpack version__: 3.11.0
__browser__: Chrome
__OS__: Mac OS High Sierra

I am able to reproduce with this simple component:

```vue
<template>
  <div>
    <pdf src="/static/example.pdf" @error="log($event)"></pdf>
  </div>
</template>

<script>
import pdf from 'vue-pdf'
export default {
  name: 'HelloWorld',
  methods: {
    log (evt) {
      console.log(evt)
    }
  },
  components: {
    pdf
  }
}
</script>
```

I have a MacBook pro with an additional screen. When I refresh the page on the lower-res screen, it works every time. When I refresh on my high-res Mac, it usually fails to load the pdf, and throws this error:
```
Error: Cannot use the same canvas during multiple render() operations. Use different canvas or ensure previous operations were cancelled or completed.
    at InternalRenderTask_initializeGraphics [as initializeGraphics] (pdf.js?9caa:9916)
    at eval (pdf.js?9caa:8873)
    at <anonymous>
```
This is the pdf I'm using:
[example.pdf](https://github.com/FranckFreiburger/vue-pdf/files/1812736/example.pdf)

It looks like it doesn't work on my Surface Pro either. So I'm assuming it's something with the screen dpi

**Comment by markhalonen** [comment]
The [jsFiddle demo](https://jsfiddle.net/fossfiddler/5k4ptmqg/145/) does not work on either screen. It just renders a white screen

**Comment by markhalonen** [comment]
Update: It works more often in Safari, and always works in Firefox.

**Comment by FranckFreiburger** [comment]
- is the error always the same ? (Cannot use the same canvas during multiple render() operations)
- does the error always appear at the first render ?

**Comment by markhalonen** [comment]
Yes, the error is always the same.

I refresh the entire page, sometimes it works, sometimes it doesn't. So I'm not sure what you mean by "first render", as I don't think anything would be cached between page refreshes.

**Comment by FranckFreiburger** [comment]
Have a look at the following issue: https://github.com/mozilla/pdf.js/issues/9456
At the moment I do not have any efficient workaround for this.

**Comment by markhalonen** [comment]
Looking at https://github.com/mozilla/pdf.js/issues/2923, the solution seems to be to create a new canvas for each render. Both the Angular and React pdf.js wrapper projects did this.

**Comment by longFeiLi** [comment]
Want to ask if there is a solution?

**Comment by longFeiLi** [comment]
@FranckFreiburger  Will release a new version number?
