### ISSUE TITLE
PDF opens in rotated orientation, but only in vuepdf (does not happen in PDF.JS)

### ISSUE THREAD

**Issue by LennieCodes** [FranckFreiburger/vue-pdf#75]
Hi, 

**The problem:**
I have a PDF document that is opening in rotated orientation, but only in vue-pdf. When I try to open the document in the pdf.js viewer.html, the file opens in vertical orientation (as it should).

**The expected result:** 
The expected output is that this PDF document should open in vertical orientation as it does in pdf.js and other PDF viewers such as adobe reader. However, when I try to open it in vue-pdf, it opens in rotated orientation.  

**File in question, and Version Details**
The file: https://github.com/LennieCodes/pdf.js/blob/master/files/img-712153249-0001.pdf
vue-pdf version: 3.2.2
vue.js version: 2.5.16
webpack version: 3.11.0
Google Chrome: 64.0.3282.186 
OS version: Windows 10

**How to reproduce:** 
1. Create an instance with vuepdf and use source file provided. You should see it open in rotated orientation.
2. Open http://mozilla.github.io/pdf.js/web/viewer.html with source file provided. You should see it open in vertical orientation. I did this by first opening the viewer, then going to "open document", and finding the file on your file system and opening it like that. 

Expected result is that the file opens in vertical orientation in vuepdf but it does not.

**Comment by LennieCodes** [comment]
@FranckFreiburger 
Did a bit of my own investigation on this. 

For this particular PDF, when I inspect this.renderPage() in pdfjsWrapper.js, line 204, pdfPage.pageInfo property is set to 270. That is the default for this particular PDF. 

However, Vue-PDF sets rotate to 0 in that same call. (Line 207) in pdfjsWrapper.js. Vue-PDF ignores whatever is inside of the pageInfo object. I believe this is what causes the PDF to rotate and display in rotated orientation.  

A possible fix would be to use the pageInfo.rotate property if rotate passed into methods is undefined.

**Comment by andysangyee** [comment]
I'm getting this problem too with some documents uploaded by a client.

I have a suggestion about rotation: 
The Vue-PDF rotation could be additive on top of the rotation specified in pdfPage.pageInfo. So always use the rotation from pdfPage.pageInfo and then add in whatever rotation (if any) specified from the client's call to the API.
