### ISSUE TITLE
base64 方式乱码

### ISSUE THREAD

**Issue by wubodanran** [FranckFreiburger/vue-pdf#84]
![image](https://user-images.githubusercontent.com/29586966/38790409-bada14d0-4173-11e8-9575-d57767a0c822.png)

浏览器直接访问正常显示.

**Comment by TigerLiv** [comment]
import pdf from 'vue-pdf';
[eslint] Missing file extension "vue" for "vue-pdf" [import/extensions]
我的引入时会报这个错  你的有吗  这个怎么解决
