### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ccaa7530** [FranckFreiburger/vue-pdf#85]
<code>Failed to load xxxxxx: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'xxxxxx' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.</code>

Please fix CORS problem, thank you!

**Comment by ccaa7530** [comment]
Sorry , i found the problem with my cdn request header setting

**Comment by eddyson1006** [comment]
Refer to #171
