### ISSUE TITLE
Naming conflict with Glyphlist.js objects on dynamic image urls with a component

### ISSUE THREAD

**Issue by jamiecarter7** [FranckFreiburger/vue-pdf#86]
I have a very obscure issue using this module.

I think your plugin uses pdf-dist module which has a file called glyphlist.js. Inside this is defines a long list of things.
I am using a function to display dynamic images on my site by passing data through a prop.
```
<img class="relicimg" :src="getImgUrl(relicImg)" alt="">
```
```
methods: {
    getImgUrl(url) {
      var images = require.context('../assets/', true, /\.png$/);
      return images('./' + url + '.png');
    },
}
```
```
  computed: {
    relicImg() {
      const camelised = this.camelise(this.title);
      return `relics/${camelised}`;
    },
  },
```
So I am passing a name string from an object, specifically the string 'Black Star'. This is run through the computer and methods above to return a url (string). Which is then passed to the getImgUrl() function. 
At this point vue is looking for an image 'blackStar' and states it cannot find it. The file is present in the correct folder and the name is correct. 200 other items folllowing the same method show correctly. When i rename the object.name to anything other than 'Black Star' along with renaming the image it works. 
The issue lies in the fact that Glyphlist.js has an object that contains the word blackstar. I think this is causing the image to fail to be found.

**Comment by FranckFreiburger** [comment]
is this problem still present?
