### ISSUE TITLE
Tag new version with master branch changes

### ISSUE THREAD

**Issue by jeffersoncardoso** [FranckFreiburger/vue-pdf#87]
Hi guys,

i had a lot of problems related to multiple page changes and zooming using the version 3.2.2 from NPM. I updated to master branch and they were all solved by #77.

For now i am using the master branch, but would like to ask if you can put this changes into a new version.  I am using this library into public organization system and its been very helpful.

Thanks!!

**Comment by FranckFreiburger** [comment]
ok, 3.2.3 has just been published
