### ISSUE TITLE
Error: Worker was destroyed

### ISSUE THREAD

**Issue by philefstat** [FranckFreiburger/vue-pdf#9]
Getting this error when I go to another component and come back to the component that includes the pdf. It works fine on first visit to the component.

`Error: Worker was destroyed
    at _fetchDocument (eval at <anonymous> (app.js:6530), <anonymous>:2541:27)
    at eval (eval at <anonymous> (app.js:6530), <anonymous>:2527:12)
    at <anonymous>`

I tried to reproduce it with this [jsfiddle](https://jsfiddle.net/9zm9c1sf/63/), but couldn't get the same error...

Any ideas?

**Comment by philefstat** [comment]
Solved by setting 
`PDFJS.disableWorker = true`

**Comment by FranckFreiburger** [comment]
I have to investigate the issue further. disableWorker = true should be considered as a workaround.

**Comment by philefstat** [comment]
@FranckFreiburger one alternative might be to explicitly set the worker in the created hook. 

Something like `PDFJS.workerSrc = 'pdfjs/build/pdf.worker.js'`

**Comment by Say-healer** [comment]
Where would the `PDFJS.disableWorker = true` go into effect?

**Comment by guguzhy** [comment]
where set the PDFJS.disableWorker = true , i tried in the created () lift-time ,i see the PDFJS.disableWorker is 
true ,but the error still exist

**Comment by jdemoort** [comment]
Hi,
Tried both PDFJS.disableWorker=true and setting PDFJS.workerSrc without success.
Any other suggestions?

Thanks!

**Comment by alexandregodet** [comment]
Hi, same problem here.
The only solution that worked for me was to set the doc src to null value just after calling the print() method.

Html:
`<pdf ref="invoice" :src="pdf_src"></pdf>`

JS:
`this.$refs.invoice.print()`
`setTimeout(() => {
   this.pdf_src = null
}, 500)`

By doing that, the destroy method will never  be called (https://github.com/FranckFreiburger/vue-pdf/blob/master/src/pdf.vue#L178)

It's just a workaround

**Comment by ChenMachluf** [comment]
That little fix solve the problem for me.
https://github.com/mozilla/pdf.js/issues/8738
hope it will merge soon

**Comment by FranckFreiburger** [comment]
@ChenMachluf thanks for your fix !
Since several people are waiting for this fix, I commit your 2nd proposition while https://github.com/mozilla/pdf.js/pull/8738 is pending.
