### ISSUE TITLE
IOS8 import pdf from 'vue-pdf' , white screen

### ISSUE THREAD

**Issue by 2014guai** [FranckFreiburger/vue-pdf#93]
IOS8.1.2 import pdf from 'vue-pdf' , white screen.
Can I use other way to use this?

**Comment by 2014guai** [comment]
pdfjsWrapper.js line 223, u use const ios8 throw error.

**Comment by Ding95** [comment]
in iOS9 same problem

**Comment by Ding95** [comment]
modify pdfjsWrapper.js line 223 'const'  to 'var', enjoy!

**Comment by FranckFreiburger** [comment]
vue-pdf@4.0.0
